var COMPILED=true;var goog=goog||{};goog.global=this;goog.global.CLOSURE_UNCOMPILED_DEFINES;goog.global.CLOSURE_DEFINES;goog.isDef=function(val){return val!==void 0;};goog.exportPath_=function(name,opt_object,opt_objectToExportTo){var parts=name.split('.');var cur=opt_objectToExportTo||goog.global;if(!(parts[0]in cur)&&cur.execScript){cur.execScript('var '+parts[0]);}
for(var part;parts.length&&(part=parts.shift());){if(!parts.length&&goog.isDef(opt_object)){cur[part]=opt_object;}else if(cur[part]){cur=cur[part];}else{cur=cur[part]={};}}};goog.define=function(name,defaultValue){var value=defaultValue;if(!COMPILED){if(goog.global.CLOSURE_UNCOMPILED_DEFINES&&Object.prototype.hasOwnProperty.call(goog.global.CLOSURE_UNCOMPILED_DEFINES,name)){value=goog.global.CLOSURE_UNCOMPILED_DEFINES[name];}else if(goog.global.CLOSURE_DEFINES&&Object.prototype.hasOwnProperty.call(goog.global.CLOSURE_DEFINES,name)){value=goog.global.CLOSURE_DEFINES[name];}}
goog.exportPath_(name,value);};goog.DEBUG=true;goog.define('goog.LOCALE','en');goog.define('goog.TRUSTED_SITE',true);goog.define('goog.STRICT_MODE_COMPATIBLE',false);goog.provide=function(name){if(!COMPILED){if(goog.isProvided_(name)){throw Error('Namespace "'+name+'" already declared.');}
delete goog.implicitNamespaces_[name];var namespace=name;while((namespace=namespace.substring(0,namespace.lastIndexOf('.')))){if(goog.getObjectByName(namespace)){break;}
goog.implicitNamespaces_[namespace]=true;}}
goog.exportPath_(name);};goog.setTestOnly=function(opt_message){if(COMPILED&&!goog.DEBUG){opt_message=opt_message||'';throw Error('Importing test-only code into non-debug environment'+
opt_message?': '+opt_message:'.');}};goog.forwardDeclare=function(name){};if(!COMPILED){goog.isProvided_=function(name){return!goog.implicitNamespaces_[name]&&goog.isDefAndNotNull(goog.getObjectByName(name));};goog.implicitNamespaces_={};}
goog.getObjectByName=function(name,opt_obj){var parts=name.split('.');var cur=opt_obj||goog.global;for(var part;part=parts.shift();){if(goog.isDefAndNotNull(cur[part])){cur=cur[part];}else{return null;}}
return cur;};goog.globalize=function(obj,opt_global){var global=opt_global||goog.global;for(var x in obj){global[x]=obj[x];}};goog.addDependency=function(relPath,provides,requires){if(goog.DEPENDENCIES_ENABLED){var provide,require;var path=relPath.replace(/\\/g,'/');var deps=goog.dependencies_;for(var i=0;provide=provides[i];i++){deps.nameToPath[provide]=path;if(!(path in deps.pathToNames)){deps.pathToNames[path]={};}
deps.pathToNames[path][provide]=true;}
for(var j=0;require=requires[j];j++){if(!(path in deps.requires)){deps.requires[path]={};}
deps.requires[path][require]=true;}}};goog.define('goog.ENABLE_DEBUG_LOADER',true);goog.require=function(name){if(!COMPILED){if(goog.isProvided_(name)){return;}
if(goog.ENABLE_DEBUG_LOADER){var path=goog.getPathFromDeps_(name);if(path){goog.included_[path]=true;goog.writeScripts_();return;}}
var errorMessage='goog.require could not find: '+name;if(goog.global.console){goog.global.console['error'](errorMessage);}
throw Error(errorMessage);}};goog.basePath='';goog.global.CLOSURE_BASE_PATH;goog.global.CLOSURE_NO_DEPS=true;goog.global.CLOSURE_IMPORT_SCRIPT;goog.nullFunction=function(){};goog.identityFunction=function(opt_returnValue,var_args){return opt_returnValue;};goog.abstractMethod=function(){throw Error('unimplemented abstract method');};goog.addSingletonGetter=function(ctor){ctor.getInstance=function(){if(ctor.instance_){return ctor.instance_;}
if(goog.DEBUG){goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=ctor;}
return ctor.instance_=new ctor;};};goog.instantiatedSingletons_=[];goog.DEPENDENCIES_ENABLED=!COMPILED&&goog.ENABLE_DEBUG_LOADER;if(goog.DEPENDENCIES_ENABLED){goog.included_={};goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}};goog.inHtmlDocument_=function(){var doc=goog.global.document;return typeof doc!='undefined'&&'write'in doc;};goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH){goog.basePath=goog.global.CLOSURE_BASE_PATH;return;}else if(!goog.inHtmlDocument_()){return;}
var doc=goog.global.document;var scripts=doc.getElementsByTagName('script');for(var i=scripts.length-1;i>=0;--i){var src=scripts[i].src;var qmark=src.lastIndexOf('?');var l=qmark==-1?src.length:qmark;if(src.substr(l-7,7)=='base.js'){goog.basePath=src.substr(0,l-7);return;}}};goog.importScript_=function(src){var importScript=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_;if(!goog.dependencies_.written[src]&&importScript(src)){goog.dependencies_.written[src]=true;}};goog.writeScriptTag_=function(src){if(goog.inHtmlDocument_()){var doc=goog.global.document;if(doc.readyState=='complete'){var isDeps=/\bdeps.js$/.test(src);if(isDeps){return false;}else{throw Error('Cannot write "'+src+'" after document load');}}
doc.write('<script type="text/javascript" src="'+src+'"></'+'script>');return true;}else{return false;}};goog.writeScripts_=function(){var scripts=[];var seenScript={};var deps=goog.dependencies_;function visitNode(path){if(path in deps.written){return;}
if(path in deps.visited){if(!(path in seenScript)){seenScript[path]=true;scripts.push(path);}
return;}
deps.visited[path]=true;if(path in deps.requires){for(var requireName in deps.requires[path]){if(!goog.isProvided_(requireName)){if(requireName in deps.nameToPath){visitNode(deps.nameToPath[requireName]);}else{throw Error('Undefined nameToPath for '+requireName);}}}}
if(!(path in seenScript)){seenScript[path]=true;scripts.push(path);}}
for(var path in goog.included_){if(!deps.written[path]){visitNode(path);}}
for(var i=0;i<scripts.length;i++){if(scripts[i]){goog.importScript_(goog.basePath+scripts[i]);}else{throw Error('Undefined script input');}}};goog.getPathFromDeps_=function(rule){if(rule in goog.dependencies_.nameToPath){return goog.dependencies_.nameToPath[rule];}else{return null;}};goog.findBasePath_();if(!goog.global.CLOSURE_NO_DEPS){goog.importScript_(goog.basePath+'deps.js');}}
goog.typeOf=function(value){var s=typeof value;if(s=='object'){if(value){if(value instanceof Array){return'array';}else if(value instanceof Object){return s;}
var className=Object.prototype.toString.call((value));if(className=='[object Window]'){return'object';}
if((className=='[object Array]'||typeof value.length=='number'&&typeof value.splice!='undefined'&&typeof value.propertyIsEnumerable!='undefined'&&!value.propertyIsEnumerable('splice'))){return'array';}
if((className=='[object Function]'||typeof value.call!='undefined'&&typeof value.propertyIsEnumerable!='undefined'&&!value.propertyIsEnumerable('call'))){return'function';}}else{return'null';}}else if(s=='function'&&typeof value.call=='undefined'){return'object';}
return s;};goog.isNull=function(val){return val===null;};goog.isDefAndNotNull=function(val){return val!=null;};goog.isArray=function(val){return goog.typeOf(val)=='array';};goog.isArrayLike=function(val){var type=goog.typeOf(val);return type=='array'||type=='object'&&typeof val.length=='number';};goog.isDateLike=function(val){return goog.isObject(val)&&typeof val.getFullYear=='function';};goog.isString=function(val){return typeof val=='string';};goog.isBoolean=function(val){return typeof val=='boolean';};goog.isNumber=function(val){return typeof val=='number';};goog.isFunction=function(val){return goog.typeOf(val)=='function';};goog.isObject=function(val){var type=typeof val;return type=='object'&&val!=null||type=='function';};goog.getUid=function(obj){return obj[goog.UID_PROPERTY_]||(obj[goog.UID_PROPERTY_]=++goog.uidCounter_);};goog.hasUid=function(obj){return!!obj[goog.UID_PROPERTY_];};goog.removeUid=function(obj){if('removeAttribute'in obj){obj.removeAttribute(goog.UID_PROPERTY_);}
try{delete obj[goog.UID_PROPERTY_];}catch(ex){}};goog.UID_PROPERTY_='closure_uid_'+((Math.random()*1e9)>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(obj){var type=goog.typeOf(obj);if(type=='object'||type=='array'){if(obj.clone){return obj.clone();}
var clone=type=='array'?[]:{};for(var key in obj){clone[key]=goog.cloneObject(obj[key]);}
return clone;}
return obj;};goog.bindNative_=function(fn,selfObj,var_args){return(fn.call.apply(fn.bind,arguments));};goog.bindJs_=function(fn,selfObj,var_args){if(!fn){throw new Error();}
if(arguments.length>2){var boundArgs=Array.prototype.slice.call(arguments,2);return function(){var newArgs=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(newArgs,boundArgs);return fn.apply(selfObj,newArgs);};}else{return function(){return fn.apply(selfObj,arguments);};}};goog.bind=function(fn,selfObj,var_args){if(Function.prototype.bind&&Function.prototype.bind.toString().indexOf('native code')!=-1){goog.bind=goog.bindNative_;}else{goog.bind=goog.bindJs_;}
return goog.bind.apply(null,arguments);};goog.partial=function(fn,var_args){var args=Array.prototype.slice.call(arguments,1);return function(){var newArgs=args.slice();newArgs.push.apply(newArgs,arguments);return fn.apply(this,newArgs);};};goog.mixin=function(target,source){for(var x in source){target[x]=source[x];}};goog.now=(goog.TRUSTED_SITE&&Date.now)||(function(){return+new Date();});goog.globalEval=function(script){if(goog.global.execScript){goog.global.execScript(script,'JavaScript');}else if(goog.global.eval){if(goog.evalWorksForGlobals_==null){goog.global.eval('var _et_ = 1;');if(typeof goog.global['_et_']!='undefined'){delete goog.global['_et_'];goog.evalWorksForGlobals_=true;}else{goog.evalWorksForGlobals_=false;}}
if(goog.evalWorksForGlobals_){goog.global.eval(script);}else{var doc=goog.global.document;var scriptElt=doc.createElement('script');scriptElt.type='text/javascript';scriptElt.defer=false;scriptElt.appendChild(doc.createTextNode(script));doc.body.appendChild(scriptElt);doc.body.removeChild(scriptElt);}}else{throw Error('goog.globalEval not available');}};goog.evalWorksForGlobals_=null;goog.cssNameMapping_;goog.cssNameMappingStyle_;goog.getCssName=function(className,opt_modifier){var getMapping=function(cssName){return goog.cssNameMapping_[cssName]||cssName;};var renameByParts=function(cssName){var parts=cssName.split('-');var mapped=[];for(var i=0;i<parts.length;i++){mapped.push(getMapping(parts[i]));}
return mapped.join('-');};var rename;if(goog.cssNameMapping_){rename=goog.cssNameMappingStyle_=='BY_WHOLE'?getMapping:renameByParts;}else{rename=function(a){return a;};}
if(opt_modifier){return className+'-'+rename(opt_modifier);}else{return rename(className);}};goog.setCssNameMapping=function(mapping,opt_style){goog.cssNameMapping_=mapping;goog.cssNameMappingStyle_=opt_style;};goog.global.CLOSURE_CSS_NAME_MAPPING;if(!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING){goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING;}
goog.getMsg=function(str,opt_values){var values=opt_values||{};for(var key in values){var value=(''+values[key]).replace(/\$/g,'$$$$');str=str.replace(new RegExp('\\{\\$'+key+'\\}','gi'),value);}
return str;};goog.getMsgWithFallback=function(a,b){return a;};goog.exportSymbol=function(publicPath,object,opt_objectToExportTo){goog.exportPath_(publicPath,object,opt_objectToExportTo);};goog.exportProperty=function(object,publicName,symbol){object[publicName]=symbol;};goog.inherits=function(childCtor,parentCtor){function tempCtor(){};tempCtor.prototype=parentCtor.prototype;childCtor.superClass_=parentCtor.prototype;childCtor.prototype=new tempCtor();childCtor.prototype.constructor=childCtor;childCtor.base=function(me,methodName,var_args){var args=Array.prototype.slice.call(arguments,2);return parentCtor.prototype[methodName].apply(me,args);};};goog.base=function(me,opt_methodName,var_args){var caller=arguments.callee.caller;if(goog.STRICT_MODE_COMPATIBLE||(goog.DEBUG&&!caller)){throw Error('arguments.caller not defined.  goog.base() cannot be used '+'with strict mode code. See '+'http://www.ecma-international.org/ecma-262/5.1/#sec-C');}
if(caller.superClass_){return caller.superClass_.constructor.apply(me,Array.prototype.slice.call(arguments,1));}
var args=Array.prototype.slice.call(arguments,2);var foundCaller=false;for(var ctor=me.constructor;ctor;ctor=ctor.superClass_&&ctor.superClass_.constructor){if(ctor.prototype[opt_methodName]===caller){foundCaller=true;}else if(foundCaller){return ctor.prototype[opt_methodName].apply(me,args);}}
if(me[opt_methodName]===caller){return me.constructor.prototype[opt_methodName].apply(me,args);}else{throw Error('goog.base called from a method of one name '+'to a method of a different name');}};goog.scope=function(fn){fn.call(goog.global);};if(!COMPILED){goog.global['COMPILED']=COMPILED;}
goog.provide('cvox.ChromeVoxJSON');if(!cvox.ChromeVoxJSON){cvox.ChromeVoxJSON={};}
if(window.JSON&&window.JSON.toString()=='[object JSON]'){cvox.ChromeVoxJSON=window.JSON;}else{(function(){function f(n){return n<10?'0'+n:n;}
if(typeof Date.prototype.toJSON!=='function'){Date.prototype.toJSON=function(key){return isFinite(this.valueOf())?this.getUTCFullYear()+'-'+f(this.getUTCMonth()+1)+'-'+
f(this.getUTCDate())+'T'+f(this.getUTCHours())+':'+
f(this.getUTCMinutes())+':'+f(this.getUTCSeconds())+'Z':'null';};Boolean.prototype.toJSON=Number.prototype.toJSON=String.prototype.toJSON=function(key){return(this.valueOf());};}
var cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,gap,indent,meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'},rep;function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+
string.replace(escapable,function(a){var c=meta[a];return typeof c==='string'?c:'\\u'+
('0000'+a.charCodeAt(0).toString(16)).slice(-4);})+'"':'"'+string+'"';}
function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==='object'&&typeof value.toJSON==='function'){value=value.toJSON(key);}
if(typeof rep==='function'){value=rep.call(holder,key,value);}
switch(typeof value){case'string':return quote(value);case'number':return isFinite(value)?String(value):'null';case'boolean':case'null':return String(value);case'object':if(!value){return'null';}
gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==='[object Array]'){length=value.length;for(i=0;i<length;i+=1){partial[i]=str(i,value)||'null';}
v=partial.length===0?'[]':gap?'[\n'+gap+partial.join(',\n'+gap)+'\n'+mind+']':'['+partial.join(',')+']';gap=mind;return v;}
if(rep&&typeof rep==='object'){length=rep.length;for(i=0;i<length;i+=1){k=rep[i];if(typeof k==='string'){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}else{for(k in value){if(Object.hasOwnProperty.call(value,k)){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}
v=partial.length===0?'{}':gap?'{\n'+gap+partial.join(',\n'+gap)+'\n'+mind+'}':'{'+partial.join(',')+'}';gap=mind;return v;}}
if(typeof cvox.ChromeVoxJSON.stringify!=='function'){cvox.ChromeVoxJSON.stringify=function(value,replacer,space){var i;gap='';indent='';if(typeof space==='number'){for(i=0;i<space;i+=1){indent+=' ';}}else if(typeof space==='string'){indent=space;}
rep=replacer;if(replacer&&typeof replacer!=='function'&&(typeof replacer!=='object'||typeof replacer.length!=='number')){throw new Error('JSON.stringify');}
return str('',{'':value});};}
if(typeof cvox.ChromeVoxJSON.parse!=='function'){cvox.ChromeVoxJSON.parse=function(text,reviver){var j;function walk(holder,key){var k,v,value=holder[key];if(value&&typeof value==='object'){for(k in value){if(Object.hasOwnProperty.call(value,k)){v=walk(value,k);if(v!==undefined){value[k]=v;}else{delete value[k];}}}}
return reviver.call(holder,key,value);}
text=String(text);cx.lastIndex=0;if(cx.test(text)){text=text.replace(cx,function(a){return'\\u'+('0000'+a.charCodeAt(0).toString(16)).slice(-4);});}
if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,'@').replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,']').replace(/(?:^|:|,)(?:\s*\[)+/g,''))){j=eval('('+text+')');return typeof reviver==='function'?walk({'':j},''):j;}
throw new SyntaxError('JSON.parse');};}}());}
goog.provide('cvox.ExtensionBridge');goog.require('cvox.ChromeVoxJSON');cvox.ExtensionBridge=function(){};cvox.ExtensionBridge.init=function(){var self=cvox.ExtensionBridge;self.messageListeners=[];self.disconnectListeners=[];if(/^chrome-extension:\/\/.*background\.html$/.test(window.location.href)){self.context=self.BACKGROUND;self.initBackground();return;}
if(chrome&&chrome.extension){self.context=self.CONTENT_SCRIPT;self.initContentScript();}};cvox.ExtensionBridge.BACKGROUND=0;cvox.ExtensionBridge.CONTENT_SCRIPT=1;cvox.ExtensionBridge.PORT_NAME='cvox.ExtensionBridge.Port';cvox.ExtensionBridge.PING_MSG='cvox.ExtensionBridge.Ping';cvox.ExtensionBridge.PONG_MSG='cvox.ExtensionBridge.Pong';cvox.ExtensionBridge.send=function(message){var self=cvox.ExtensionBridge;switch(self.context){case self.BACKGROUND:self.sendBackgroundToContentScript(message);break;case self.CONTENT_SCRIPT:self.sendContentScriptToBackground(message);break;}};cvox.ExtensionBridge.addMessageListener=function(listener){cvox.ExtensionBridge.messageListeners.push(listener);};cvox.ExtensionBridge.addDisconnectListener=function(listener){cvox.ExtensionBridge.disconnectListeners.push(listener);};cvox.ExtensionBridge.removeMessageListeners=function(){cvox.ExtensionBridge.messageListeners.length=0;};cvox.ExtensionBridge.uniqueId=function(){return cvox.ExtensionBridge.id_;};cvox.ExtensionBridge.initBackground=function(){var self=cvox.ExtensionBridge;self.portCache_=[];self.nextPongId_=1;self.id_=0;var onConnectHandler=function(port){if(port.name!=self.PORT_NAME){return;}
self.portCache_.push(port);port.onMessage.addListener(function(message){if(message[cvox.ExtensionBridge.PING_MSG]){var pongMessage={};pongMessage[cvox.ExtensionBridge.PONG_MSG]=self.nextPongId_++;port.postMessage(pongMessage);return;}
for(var i=0;i<self.messageListeners.length;i++){self.messageListeners[i](message,port);}});port.onDisconnect.addListener(function(message){for(var i=0;i<self.portCache_.length;i++){if(self.portCache_[i]==port){self.portCache_.splice(i,1);break;}}});};chrome.extension.onConnect.addListener(onConnectHandler);};cvox.ExtensionBridge.initContentScript=function(){var self=cvox.ExtensionBridge;self.connected=false;self.pingAttempts=0;self.queuedMessages=[];self.id_=-1;var onMessageHandler=function(request,sender,sendResponse){if(request&&request['srcFile']){return;}
if(request[cvox.ExtensionBridge.PONG_MSG]){self.gotPongFromBackgroundPage(request[cvox.ExtensionBridge.PONG_MSG]);}else{for(var i=0;i<self.messageListeners.length;i++){self.messageListeners[i](request,cvox.ExtensionBridge.backgroundPort);}}
sendResponse({});};chrome.extension.onMessage.addListener(onMessageHandler);self.setupBackgroundPort();self.tryToPingBackgroundPage();};cvox.ExtensionBridge.setupBackgroundPort=function(){var self=cvox.ExtensionBridge;self.backgroundPort=chrome.extension.connect({name:self.PORT_NAME});if(!self.backgroundPort){return;}
self.backgroundPort.onMessage.addListener(function(message){if(message[cvox.ExtensionBridge.PONG_MSG]){self.gotPongFromBackgroundPage(message[cvox.ExtensionBridge.PONG_MSG]);}else{for(var i=0;i<self.messageListeners.length;i++){self.messageListeners[i](message,self.backgroundPort);}}});self.backgroundPort.onDisconnect.addListener(function(event){if(!self.connected){self.backgroundPort=null;return;}
self.backgroundPort=null;self.connected=false;for(var i=0;i<self.disconnectListeners.length;i++){self.disconnectListeners[i]();}});};cvox.ExtensionBridge.tryToPingBackgroundPage=function(){var self=cvox.ExtensionBridge;if(self.connected){return;}
self.pingAttempts++;if(self.pingAttempts>5){for(var i=0;i<self.disconnectListeners.length;i++){self.disconnectListeners[i]();}
return;}
var msg={};msg[cvox.ExtensionBridge.PING_MSG]=1;if(!self.backgroundPort){self.setupBackgroundPort();}
if(self.backgroundPort){self.backgroundPort.postMessage(msg);}
window.setTimeout(cvox.ExtensionBridge.tryToPingBackgroundPage,500);};cvox.ExtensionBridge.gotPongFromBackgroundPage=function(pongId){var self=cvox.ExtensionBridge;self.connected=true;self.id_=pongId;while(self.queuedMessages.length>0){self.sendContentScriptToBackground(self.queuedMessages.shift());}};cvox.ExtensionBridge.sendContentScriptToBackground=function(message){var self=cvox.ExtensionBridge;if(!self.connected){self.queuedMessages.push(message);return;}
if(cvox.ExtensionBridge.backgroundPort){cvox.ExtensionBridge.backgroundPort.postMessage(message);}else{chrome.extension.sendMessage(message);}};cvox.ExtensionBridge.sendBackgroundToContentScript=function(message){cvox.ExtensionBridge.portCache_.forEach(function(port){port.postMessage(message);});};cvox.ExtensionBridge.init();goog.provide('constants');constants.Dir={FORWARD:'forward',BACKWARD:'backward'};constants.Point;constants.OBJECT_MAX_CHARCOUNT=1500;goog.provide('cvox.ChromeVox');goog.require('constants');goog.addDependency('../host/interface/abstract_host.js',['cvox.AbstractHost'],[]);goog.addDependency('../host/interface/tts_interface.js',['cvox.TtsInterface'],[]);goog.addDependency('../host/interface/braille_interface.js',['cvox.BrailleInterface'],[]);goog.addDependency('../host/interface/mathjax_interface.js',['cvox.MathJaxInterface'],[]);goog.addDependency('../chromevox/messages/msgs.js',['Msgs'],[]);goog.addDependency('../host/interface/abstract_earcons.js',['cvox.AbstractEarcons'],[]);goog.addDependency('../chromevox/common/key_sequence.js',['cvox.KeySequence'],[]);goog.addDependency('../chromevox/injected/navigation_manager.js',['cvox.NavigationManager'],[]);goog.addDependency('../chromevox/injected/serializer.js',['cvox.Serializer'],[]);cvox.VERBOSITY_VERBOSE=0;cvox.VERBOSITY_BRIEF=1;cvox.ChromeVox=function(){};cvox.ChromeVox.host=null;cvox.ChromeVox.tts;cvox.ChromeVox.braille;cvox.ChromeVox.mathJax;cvox.ChromeVox.isActive=true;cvox.ChromeVox.version=null;cvox.ChromeVox.earcons=null;cvox.ChromeVox.navigationManager=null;cvox.ChromeVox.serializer=null;cvox.ChromeVox.isStickyPrefOn=false;cvox.ChromeVox.stickyOverride=null;cvox.ChromeVox.keyPrefixOn=false;cvox.ChromeVox.verbosity=cvox.VERBOSITY_VERBOSE;cvox.ChromeVox.typingEcho=0;cvox.ChromeVox.keyEcho={};cvox.ChromeVox.position={};cvox.ChromeVox.isChromeOS=navigator.userAgent.indexOf('CrOS')!=-1;cvox.ChromeVox.isMac=navigator.platform.indexOf('Mac')!=-1;cvox.ChromeVox.modKeyStr;if(cvox.ChromeVox.isChromeOS){cvox.ChromeVox.modKeyStr='Shift+Search';}else if(cvox.ChromeVox.isMac){cvox.ChromeVox.modKeyStr='Ctrl+Cmd';}else{cvox.ChromeVox.modKeyStr='Shift+Alt';}
cvox.ChromeVox.sequenceSwitchKeyCodes=[];cvox.ChromeVox.visitedUrls={};cvox.ChromeVox.markInUserCommand=function(){};cvox.ChromeVox.syncToNode=function(targetNode,speakNode,opt_queueMode){};cvox.ChromeVox.executeUserCommand=function(commandName){};cvox.ChromeVox.entireDocumentIsHidden=false;cvox.ChromeVox.storeOn=function(store){store['isStickyPrefOn']=cvox.ChromeVox.isStickyPrefOn;cvox.ChromeVox.navigationManager.storeOn(store);};cvox.ChromeVox.readFrom=function(store){cvox.ChromeVox.isStickyPrefOn=store['isStickyPrefOn'];cvox.ChromeVox.navigationManager.readFrom(store);};cvox.ChromeVox.isStickyModeOn=function(){if(cvox.ChromeVox.stickyOverride!==null){return cvox.ChromeVox.stickyOverride;}else{return cvox.ChromeVox.isStickyPrefOn;}};function $(id){return document.getElementById(id);}
cvox.ChromeVox.injectChromeVoxIntoTabs=function(tabs){};cvox.ChromeVox.documentHasFocus=function(){if(!document.hasFocus()||document.hidden){return false;}
if(document.activeElement.tagName=='IFRAME'||document.activeElement.tagName=='WEBVIEW'){return false;}
return true;};goog.provide('cvox.ScriptInstaller');cvox.ScriptInstaller.blacklistPattern=/chrome:\/\/|chrome-extension:\/\//;cvox.ScriptInstaller.installScript=function(srcs,uid,opt_onload,opt_chromevoxScriptBase){if(cvox.ScriptInstaller.blacklistPattern.test(document.URL)){return false;}
if(document.querySelector('script['+uid+']')){cvox.ScriptInstaller.uninstallScript(uid);}
if(!srcs||srcs.length==0){return false;}
cvox.ScriptInstaller.installScriptHelper_(srcs,uid,opt_onload,opt_chromevoxScriptBase);return true;};cvox.ScriptInstaller.uninstallScript=function(uid){var scriptNode;if(scriptNode=document.querySelector('script['+uid+']'))
scriptNode.remove();};cvox.ScriptInstaller.installScriptHelper_=function(srcs,uid,opt_onload,opt_chromevoxScriptBase){function next(){if(srcs.length>0){cvox.ScriptInstaller.installScriptHelper_(srcs,uid,opt_onload,opt_chromevoxScriptBase);}else if(opt_onload){opt_onload();}}
var scriptSrc=srcs.shift();if(!scriptSrc){next();return;}
var xhr=new XMLHttpRequest();var url=scriptSrc+'?'+new Date().getTime();xhr.onreadystatechange=function(){if(xhr.readyState==4){var scriptText=xhr.responseText;scriptText+='\n//# sourceURL='+scriptSrc+'\n';var apiScript=document.createElement('script');apiScript.type='text/javascript';apiScript.setAttribute(uid,'1');apiScript.textContent=scriptText;if(opt_chromevoxScriptBase){apiScript.setAttribute('chromevoxScriptBase',opt_chromevoxScriptBase);}
var scriptOwner=document.head||document.body;scriptOwner.appendChild(apiScript);next();}};try{xhr.open('GET',url,true);xhr.send(null);}catch(exception){console.log('Warning: ChromeVox external script loading for '+document.location+' stopped after failing to install '+scriptSrc);next();}};goog.provide('cvox.ApiImplementation');goog.require('cvox.ChromeVox');goog.require('cvox.ExtensionBridge');goog.require('cvox.ScriptInstaller');cvox.ApiImplementation=function(){};cvox.ApiImplementation.DISCONNECT_MSG='cvox.Disconnect';cvox.ApiImplementation.init=function(opt_onload){window.addEventListener('message',cvox.ApiImplementation.portSetup,true);var scripts=[window.chrome.extension.getURL('chromevox/injected/api.js')];var didInstall=cvox.ScriptInstaller.installScript(scripts,'cvoxapi',opt_onload);if(!didInstall){console.error('Unable to install api scripts');}
cvox.ExtensionBridge.addDisconnectListener(function(){cvox.ApiImplementation.port.postMessage(cvox.ApiImplementation.DISCONNECT_MSG);cvox.ScriptInstaller.uninstallScript('cvoxapi');});};cvox.ApiImplementation.portSetup=function(event){if(event.data=='cvox.PortSetup'){cvox.ApiImplementation.port=event.ports[0];cvox.ApiImplementation.port.onmessage=function(event){cvox.ApiImplementation.dispatchApiMessage(JSON.parse(event.data));};event.stopPropagation();return false;}
return true;};cvox.ApiImplementation.dispatchApiMessage=function(message){var method;switch(message['cmd']){case'speak':method=cvox.ApiImplementation.speak;break;break;}
if(!method){throw'Unknown API call: '+message['cmd'];}
method.apply(cvox.ApiImplementation,message['args']);};function setupEndCallback_(properties,callbackId){var endCallback=function(){cvox.ApiImplementation.port.postMessage(JSON.stringify({'id':callbackId}));};if(properties){properties['endCallback']=endCallback;}}
cvox.ApiImplementation.speak=function(callbackId,textString,queueMode,properties){if(!properties){properties={};}
setupEndCallback_(properties,callbackId);var message={'target':'TTS','action':'speak','text':textString,'queueMode':queueMode,'properties':properties};cvox.ExtensionBridge.send(message);};goog.provide('KeyboardHandler');KeyboardHandler=function(){cvox.ChromeVoxKbHandler.commandHandler=this.handleCommand_.bind(this);cvox.ChromeVoxKbHandler.handlerKeyMap=cvox.KeyMap.fromNext();document.addEventListener('keydown',this.handleKeyDown_.bind(this),false);cvox.ExtensionBridge.addMessageListener(function(msg){if(msg['prefs']){var prefs=msg['prefs'];cvox.ChromeVox.isStickyPrefOn=prefs['sticky']=='true';}});cvox.ExtensionBridge.send({'target':'Prefs','action':'getPrefs'});};KeyboardHandler.prototype={handleKeyDown_:function(evt){cvox.ExtensionBridge.send({'target':'next','action':'flushNextUtterance'});evt.stickyMode=cvox.ChromeVox.isStickyPrefOn;cvox.ChromeVoxKbHandler.basicKeyDownActionsListener(evt);},handleCommand_:function(command){cvox.ExtensionBridge.send({'target':'next','action':'onCommand','command':command});}};goog.require('cvox.ApiImplementation');goog.require('KeyboardHandler');function initMin(){if(cvox.ChromeVox.isChromeOS){cvox.ApiImplementation.init();return;}
if(cvox.ChromeVox.isClassicEnabled_===undefined){window.setTimeout(function(){initMin();},500);return;}
if(cvox.ChromeVox.isClassicEnabled_)
return;new KeyboardHandler();}
initMin();
