(function(){function e(b,a){return b.type=a}
var f="push",k="call",l="",m=" ",p="!",q='"',r="#",s="$",t="%",u="&",w="'",x="(",y=")",z="*",A="+",B=",",C="-",D=".",E="/",F="0",G="1",H="2",I="3",J="4",K="5",L="6",M="7",N="8",O="9",P=":",Q=";",R="<",S="=",aa=">",ba="?",ca="@",da="A",ea="AltLeft",fa="ArrowDown",ga="ArrowLeft",ha="ArrowRight",ia="ArrowUp",ja="B",ka="Backslash",la="Backspace",ma="BracketLeft",na="BracketRight",oa="C",pa="Comma",qa="ControlLeft",ra="Convert",sa="D",ta="Digit0",ua="Digit1",va="Digit2",wa="Digit3",xa="Digit4",ya="Digit5",
za="Digit6",Aa="Digit7",Ba="Digit8",Ca="Digit9",Da="E",Ea="Enter",Fa="Equal",Ga="F",Ha="G",Ia="Globe",Ja="H",Ka="HideKeyboard",La="I",Ma="IntlRo",Na="IntlYen",Oa="J",Pa="K",Qa="KeyA",Ra="KeyB",Sa="KeyC",Ta="KeyD",Ua="KeyE",Va="KeyF",Wa="KeyG",Xa="KeyH",Ya="KeyI",Za="KeyJ",$a="KeyK",ab="KeyL",bb="KeyM",cb="KeyN",db="KeyO",eb="KeyP",fb="KeyQ",gb="KeyR",hb="KeyS",ib="KeyT",jb="KeyU",kb="KeyV",lb="KeyW",mb="KeyX",nb="KeyY",ob="KeyZ",pb="L",qb="M",rb="Menu",sb="Minus",tb="N",ub="NonConvert",vb="O",wb=
"OsLeft",xb="P",yb="Period",zb="Q",Ab="Quote",Bb="R",Cb="S",Db="Semicolon",Eb="ShiftLeft",Fb="ShiftRight",Gb="Slash",Hb="Space",Ib="T",Jb="Tab",Kb="Toggle",Lb="U",Mb="V",Nb="W",Ob="X",Pb="Y",Qb="Z",Rb="[",T="\\",Sb="]",Tb="^",Ub="_",Vb="`",Wb="a",Xb="alt",Yb="b",Zb="c",$b="caps lock",ac="ctrl",bc="d",cc="e",dc="f",ec="g",fc="h",gc="i",hc="inputview-arrow-key ",ic="inputview-backspace-icon",jc="inputview-down-key",kc="inputview-enter-icon",lc="inputview-globe-icon",mc="inputview-hide-keyboard-icon",
nc="inputview-jp-ime-switch",oc="inputview-left-key",pc="inputview-right-key",qc="inputview-shift-icon",rc="inputview-tab-icon",sc="inputview-up-key",tc="j",uc="jp",vc="jp-kana",wc="jpkbd",xc="jpkbd-k-",yc="k",zc="l",Ac="m",Bc="n",Cc="o",Dc="p",Ec="q",Fc="r",Gc="s",Hc="string",Ic="t",Jc="u",Kc="v",Lc="w",Mc="x",Nc="y",Oc="z",Pc="{",Qc="|",Rc="}",Sc="~",Tc="\u22ee",Uc="\u3001",Vc="\u3002",Wc="\u300c",Xc="\u300d",Yc="\u3041",Zc="\u3042",$c="\u3043",ad="\u3044",bd="\u3045",cd="\u3046",dd="\u3047",ed=
"\u3048",fd="\u3049",gd="\u304a",hd="\u304b",id="\u304b\u306a",jd="\u304d",kd="\u304f",ld="\u3051",md="\u3053",nd="\u3055",od="\u3057",pd="\u3059",qd="\u305b",rd="\u305d",sd="\u305f",td="\u3061",ud="\u3063",vd="\u3064",wd="\u3066",xd="\u3068",yd="\u306a",zd="\u306b",Ad="\u306c",Bd="\u306d",Cd="\u306e",Dd="\u306f",Ed="\u3072",Fd="\u3075",Gd="\u3078",Hd="\u307b",Id="\u307e",Jd="\u307f",Kd="\u3080",Ld="\u3081",Md="\u3082",Nd="\u3083",Od="\u3084",Pd="\u3085",Qd="\u3086",Rd="\u3087",Sd="\u3088",Td="\u3089",
Ud="\u308a",Vd="\u308b",Wd="\u308c",Xd="\u308d",Yd="\u308f",Zd="\u3092",$d="\u3093",ae="\u309b",be="\u309c",ce="\u30fb",de="\u30fc",ee="\u82f1\u6570",fe="\u82f1\u6f22";function U(b,a,c,h){V.splice.apply(b,ge(arguments,1))}function ge(b,a,c){return 2>=arguments.length?V.slice[k](b,a):V.slice[k](b,a,c)}function W(b){var a={toState:1,iconCssClass:qc,type:5};a.id=b?Eb:Fb;a.supportSticky=!1;return X(a)}function Y(b,a){var c={};c.name=a;e(c,35);c.id=b;c.textCssClass=nc;return X(c)}
function Z(b){var a={iconCssClass:hc};0==b?(a.id=ia,a.iconCssClass+=sc,e(a,15)):1==b?(a.id=fa,a.iconCssClass+=jc,e(a,16)):2==b?(a.id=ga,a.iconCssClass+=oc,e(a,17)):3==b&&(a.id=ha,a.iconCssClass+=pc,e(a,18));return X(a)}function X(b){var a={},c;for(c in b)a[c]=b[c];return{spec:a}};var V=Array.prototype,$=V.forEach?function(b,a,c){V.forEach[k](b,a,c)}:function(b,a,c){for(var h=b.length,v=typeof b==Hc?b.split(l):b,n=0;n<h;n++)n in v&&a[k](c,v[n],n,b)};(function(){function b(b,c){var d=[];d[f](Y(Kb,fe));$(b,function(b,h){var g={};g.id=a[h];e(g,6);g.characters=b;g.keyCode=c[h];d[f](X(g))});U(d,14,0,X({iconCssClass:ic,type:13,id:la}));U(d,15,0,X({iconCssClass:rc,type:14,id:Jb}));U(d,28,0,X({toState:4,name:$b,type:5,id:wb}));U(d,41,0,X({iconCssClass:kc,type:12,id:Ea}));U(d,42,0,W(!0));d[f](W(!1));d[f](X({iconCssClass:lc,type:27,id:Ia}));d[f](X({name:Tc,toKeyset:void 0,type:26,id:rb}));d[f](X({toState:8,name:ac,type:5,id:qa}));d[f](X({toState:16,name:Xb,
type:5,id:ea}));d[f](Y(ub,ee));d[f](X({name:m,type:11,id:Hb}));d[f](Y(ra,id));d[f](Z(2));d[f](Z(3));d[f](X({iconCssClass:mc,type:19,id:Ka}));var h={};$(d,function(a,b){h[a.spec.id]=xc+b});var g=[];g.keyList=d;g.mapping=h;g.layout=wc;g.hasAltGrKey=!1;g.hasCompactKeyboard=!1;g.showMenuKey=!0;return g}var a=[ua,va,wa,xa,ya,za,Aa,Ba,Ca,ta,sb,Fa,Na,fb,lb,Ua,gb,ib,nb,jb,Ya,db,eb,ma,na,Qa,hb,Ta,Va,Wa,Xa,Za,$a,ab,Db,Ab,ka,ob,mb,Sa,kb,Ra,cb,bb,pa,yb,Gb,Ma],c=[49,50,51,52,53,54,55,56,57,48,189,187,255,81,87,
69,82,84,89,85,73,79,80,219,221,65,83,68,70,71,72,74,75,76,186,222,220,90,88,67,86,66,78,77,188,190,191,193],h=b([[G,p],[H,q],[I,r],[J,s],[K,t],[L,u],[M,w],[N,x],[O,y],[F,F],[C,S],[Tb,Sc],[T,Qc],[Ec,zb],[Lc,Nb],[cc,Da],[Fc,Bb],[Ic,Ib],[Nc,Pb],[Jc,Lb],[gc,La],[Cc,vb],[Dc,xb],[ca,Vb],[Rb,Pc],[Wb,da],[Gc,Cb],[bc,sa],[dc,Ga],[ec,Ha],[fc,Ja],[tc,Oa],[yc,Pa],[zc,pb],[Q,A],[P,z],[Sb,Rc],[Oc,Qb],[Mc,Ob],[Zb,oa],[Kc,Mb],[Yb,ja],[Bc,tb],[Ac,qb],[B,R],[D,aa],[E,ba],[T,Ub]],c);h.id=uc;google.ime.chrome.inputview.onConfigLoaded(h);
c=b([[Ad],[Fd],[Zc,Yc],[cd,bd],[ed,dd],[gd,fd],[Od,Nd],[Qd,Pd],[Sd,Rd],[Yd,Zd],[Hd],[Gd],[de],[sd],[wd],[ad,$c],[pd],[hd],[$d],[yd],[zd],[Td],[qd],[ae],[be,Wc],[td],[xd],[od],[Dd],[jd],[kd],[Id],[Cd],[Ud],[Wd],[ld],[Kd,Xc],[vd,ud],[nd],[rd],[Ed],[md],[Jd],[Md],[Bd,Uc],[Vd,Vc],[Ld,ce],[Xd]],c);c.id=vc;google.ime.chrome.inputview.onConfigLoaded(c)})();})();
