(function(){function c(b,a){return b.type=a}
var d="data",e="push",k="length",m=".",aa="ArrowDown",ba="ArrowLeft",ca="ArrowRight",da="ArrowUp",n="ShiftLeft",p="ShiftRight",ea="The number of switcher key spec is less than the number of switcher keys in the keyset.",fa="The number of switcher key spec is more than the number of switcher keys in the keyset.",ga="compactkbd-k-",ha="compactkbd-k-key-",q="compactkbd-numberpad",r="compactkbd-qwerty",ia="inputview-arrow-key ",s="inputview-backspace-icon",ja="inputview-down-key",t="inputview-enter-icon",
u="inputview-font-small",v="inputview-globe-icon",w="inputview-hide-keyboard-icon",ka="inputview-left-key",x="inputview-menu-icon",la="inputview-right-key",y="inputview-shift-icon",ma="inputview-up-key",z="more symbols layout",A="number and symbol layout";
function B(b){for(var a=[],f={},g=0;g<b[d][k];g++){var l=b[d][g];l==C&&(l.toKeyset=b.id.split(m)[0]);var h;h=l;h.id=l.id?l.id:ha+g;h.type||c(h,22);var l={},K=void 0;for(K in h)l[K]=h[K];h={spec:l};a[e](h);f[h.spec.id]=ga+g}return{keyList:a,mapping:f,layout:b.layout}}function D(b,a){for(var f=0,g=0;g<b[k];g++)if(b[g]==E){if(f>=a[k]){console.error(ea);return}var l=a[f++],h;for(h in b[g])l[h]=b[g][h];b[g]=l}f<a[k]-1&&console.error(fa)}function F(b,a,f,g){G.splice.apply(b,na(arguments,1))}
function na(b,a,f){return 2>=arguments[k]?G.slice.call(b,a):G.slice.call(b,a,f)}function H(b){var a={toState:1,iconCssClass:y,type:5};a.id=b?n:p;a.supportSticky=!1;return I(a)}function J(b){var a={iconCssClass:ia};0==b?(a.id=da,a.iconCssClass+=ma,c(a,15)):1==b?(a.id=aa,a.iconCssClass+=ja,c(a,16)):2==b?(a.id=ba,a.iconCssClass+=ka,c(a,17)):3==b&&(a.id=ca,a.iconCssClass+=la,c(a,18));return I(a)}function I(b){var a={},f;for(f in b)a[f]=b[f];return{spec:a}};var L={iconCssClass:s,type:13,id:"Backspace"},M={iconCssClass:t,type:12,id:"Enter"},N={iconCssClass:w,type:19,id:"HideKeyboard"},O={name:" ",type:11,id:"Space"},E={type:21},C={iconCssClass:x,type:26,id:"Menu"};var G=Array.prototype;for(var oa=[["`","~"],["1","!"],["2","@"],["3","#"],["4","$"],["5","%"],["6","^"],["7","&"],["8","*"],["9","("],["0",")"],["-","_"],["=","+"],["q","Q"],["w","W"],["e","E"],["r","R"],["t","T"],["y","Y"],["u","U"],["i","I"],["o","O"],["p","P"],["[","{"],["]","}"],["a","A"],["s","S"],["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L"],[";",":"],["'",'"'],["\\","|"],["<",">","|","\u00a6"],["z","Z"],["x","X"],["c","C"],["v","V"],["b","B"],["n","N"],["m","M"],[",","<"],[m,">"],["/","?"],
[" "," "]],P=[],pa={},qa=[],ra="Backquote Digit1 Digit2 Digit3 Digit4 Digit5 Digit6 Digit7 Digit8 Digit9 Digit0 Minus Equal KeyQ KeyW KeyE KeyR KeyT KeyY KeyU KeyI KeyO KeyP BracketLeft BracketRight KeyA KeyS KeyD KeyF KeyG KeyH KeyJ KeyK KeyL Semicolon Quote Backslash IntlBackslash KeyZ KeyX KeyC KeyV KeyB KeyN KeyM Comma Period Slash".split(" "),Q=0;Q<oa[k]-1;Q++){var R={};R.id=ra[Q];c(R,6);R.characters=oa[Q];R.keyCode=qa[Q];var S=I(R);P[e](S)}F(P,13,0,I({iconCssClass:s,type:13,id:"Backspace"}));
F(P,14,0,I({iconCssClass:"inputview-tab-icon",type:14,id:"Tab"}));F(P,27,0,I({toState:4,name:"caps lock",type:5,id:"OsLeft"}));F(P,40,0,I({iconCssClass:t,type:12,id:"Enter"}));F(P,41,0,H(!0));P[e](H(!1));P[e](I({iconCssClass:v,type:27,id:"Globe"}));P[e](I({iconCssClass:x,toKeyset:void 0,type:26,id:"Menu"}));P[e](I({toState:8,name:"ctrl",type:5,id:"ControlLeft"}));P[e](I({toState:16,name:"alt",type:5,id:"AltLeft"}));P[e](I({name:" ",type:11,id:"Space"}));P[e](I({type:42,id:"enSwitcher"}));
P[e](I({toState:2,name:"alt gr",type:5,id:"AltRight"}));P[e](J(2));P[e](J(3));P[e](I({iconCssClass:w,type:19,id:"HideKeyboard"}));for(Q=0;Q<P[k];Q++)S=P[Q],pa[S.spec.id]="102kbd-k-"+Q;var T=[];T.keyList=P;T.mapping=pa;T.layout="102kbd";T.hasAltGrKey=!0;T.hasCompactKeyboard=!1;T.showMenuKey=!0;T.id="ca-eng";google.ime.chrome.inputview.onConfigLoaded(T);
var U={id:"ca-eng.compact.qwerty",layout:r,data:[{text:"q",hintText:"1"},{text:"w",hintText:"2"},{text:"e",hintText:"3",moreKeys:["\u00e8","\u00e9","\u00ea","\u00eb","\u0113"]},{text:"r",hintText:"4"},{text:"t",hintText:"5"},{text:"y",hintText:"6"},{text:"u",hintText:"7",moreKeys:["\u00fb","\u00fc","\u00f9","\u00fa","\u016b"]},{text:"i",hintText:"8",moreKeys:["\u00ee","\u00ef","\u00ed","\u012b","\u00ec"]},{text:"o",hintText:"9",moreKeys:"\u00f4\u00f6\u00f2\u00f3\u0153\u00f8\u014d\u00f5".split("")},
{text:"p",hintText:"0"},L,{text:"a",marginLeftPercent:.33,moreKeys:"\u00e0\u00e1\u00e2\u00e4\u00e6\u00e3\u00e5\u0101".split("")},{text:"s",moreKeys:["\u00df"]},{text:"d"},{text:"f"},{text:"g"},{text:"h"},{text:"j"},{text:"k"},{text:"l"},M,{toState:1,iconCssClass:y,type:5,id:n,supportSticky:!0},{text:"z"},{text:"x"},{text:"c",moreKeys:["\u00e7"]},{text:"v"},{text:"b"},{text:"n",moreKeys:["\u00f1"]},{text:"m"},{text:"!",moreKeys:["\u00a1"]},{text:"?",moreKeys:["\u00bf"]},{toState:1,iconCssClass:y,type:5,
id:p,supportSticky:!0},E,{iconCssClass:v,type:27,id:"Globe"},C,{text:"/",isGrey:!0,onContext:{email:{text:"@"}}},O,{text:",",isGrey:!0,onContext:{email:{text:".com",textCssClass:u},url:{text:".com",textCssClass:u}}},{text:m,isGrey:!0,moreKeys:"#!\\?-:'@".split("")},N]},V={id:"ca-eng.compact.symbol",layout:r,data:[{text:"1",moreKeys:["\u00b9","\u00bd","\u2153","\u00bc","\u215b"]},{text:"2",moreKeys:["\u00b2","\u2154"]},{text:"3",moreKeys:["\u00b3","\u00be","\u215c"]},{text:"4",moreKeys:["\u2074"]},
{text:"5",moreKeys:["\u215d"]},{text:"6"},{text:"7",moreKeys:["\u215e"]},{text:"8"},{text:"9"},{text:"0",moreKeys:["\u207f","\u2205"]},L,{text:"@",marginLeftPercent:.33},{text:"#"},{text:"$",moreKeys:["\u00a2","\u00a3","\u20ac","\u00a5","\u20b1"]},{text:"%",moreKeys:["\u2030"]},{text:"&"},{text:"-",moreKeys:["_","\u2013","\u2014","\u00b7"]},{text:"+",moreKeys:["\u00b1"]},{text:"(",moreKeys:["{","<","["]},{text:")",moreKeys:["}",">","]"]},M,E,{text:"\\"},{text:"="},{text:"*",moreKeys:["\u2020","\u2021",
"\u2605"]},{text:'"',moreKeys:["\u201c","\u201e","\u201d","\u00ab","\u00bb"]},{text:"'",moreKeys:["\u2018","\u201a","\u2019","\u2039","\u203a"]},{text:":"},{text:";"},{text:"!",moreKeys:["\u00a1"]},{text:"?",moreKeys:["\u00bf"]},E,E,{text:"_",isGrey:!0},C,{text:"/",isGrey:!0},O,{text:",",isGrey:!0},{text:m,isGrey:!0,moreKeys:["\u2026"]},N]},W={id:"ca-eng.compact.more",layout:r,data:[{text:"~"},{text:"`"},{text:"|"},{text:"\u2022",moreKeys:["\u266a","\u2665","\u2660","\u2666","\u2663"]},{text:"\u23b7"},
{text:"\u03c0",moreKeys:["\u03a0"]},{text:"\u00f7"},{text:"\u00d7"},{text:"\u00b6",moreKeys:["\u00a7"]},{text:"\u0394"},L,{text:"\u00a3",marginLeftPercent:.33},{text:"\u00a2"},{text:"\u20ac"},{text:"\u00a5"},{text:"^",moreKeys:["\u2191","\u2193","\u2190","\u2192"]},{text:"\u00b0",moreKeys:["\u2032","\u2033"]},{text:"=",moreKeys:["\u2260","\u2248","\u221e"]},{text:"{"},{text:"}"},M,E,{text:"\\"},{text:"\u00a9"},{text:"\u00ae"},{text:"\u2122"},{text:"\u2105"},{text:"["},{text:"]"},{text:"\u00a1"},{text:"\u00bf"},
E,E,{text:"<",isGrey:!0,moreKeys:["\u2039","\u2264","\u00ab"]},C,{text:">",isGrey:!0,moreKeys:["\u203a","\u2265","\u00bb"]},O,{text:",",isGrey:!0},{text:m,isGrey:!0,moreKeys:["\u2026"]},N]},X=google.ime.chrome.inputview.onConfigLoaded;D(U[d],[{name:"?123",toKeyset:V.id,toKeysetName:A}]);var Y=B(U);Y.id=U.id;Y.showMenuKey=!0;X(Y);D(V[d],[{name:"~[<",toKeyset:W.id,toKeysetName:z},{name:"~[<",toKeyset:W.id,toKeysetName:z},{name:"abc",toKeyset:U.id,toKeysetName:"main layout"}]);Y=B(V);Y.id=V.id;
Y.showMenuKey=!1;Y.noShift=!0;X(Y);D(W[d],[{name:"?123",toKeyset:V.id,toKeysetName:A},{name:"?123",toKeyset:V.id,toKeysetName:A},{name:"abc",toKeyset:U.id,toKeysetName:"main layout"}]);Y=B(W);Y.id=W.id;Y.showMenuKey=!1;Y.noShift=!0;X(Y);
var Z={number:{id:"ca-eng.compact.numberpad",layout:q,data:[{text:"-",isGrey:!0},{text:"+",isGrey:!0},{text:m,isGrey:!0},{text:"1"},{text:"2"},{text:"3"},L,{text:"*",isGrey:!0},{text:"/",isGrey:!0},{text:",",isGrey:!0},{text:"4"},{text:"5"},{text:"6"},M,{text:"(",isGrey:!0},{text:")",isGrey:!0},{text:"=",isGrey:!0},{text:"7"},{text:"8"},{text:"9",marginRightPercent:.545454},O,{text:"*"},{text:"0"},{text:"#"},N]},tel:{id:"ca-eng.compact.phonepad",layout:q,data:[{text:"-",isGrey:!0},{text:"+",isGrey:!0},
{title:"Pause",text:",",isGrey:!0,textCssClass:u},{text:"1"},{text:"2",hintText:"ABC"},{text:"3",hintText:"DEF"},L,{text:",",isGrey:!0},{text:m,isGrey:!0},{title:"Wait",text:";",isGrey:!0,textCssClass:u},{text:"4",hintText:"GHI"},{text:"5",hintText:"JKL"},{text:"6",hintText:"MNO"},M,{text:"(",isGrey:!0},{text:")",isGrey:!0},{text:"N",isGrey:!0},{text:"7",hintText:"PQRS"},{text:"8",hintText:"TUV"},{text:"9",hintText:"WXYZ",marginRightPercent:.545454},O,{text:"*"},{text:"0"},{text:"#"},N]}},sa=google.ime.chrome.inputview.onConfigLoaded;
if(Z)for(var ta in Z){var ua=Z[ta],$=B(ua);$.id=ua.id;$.showMenuKey=!1;$.noShift=!0;$.onContext=ta;sa($)};})();
