(function(){function a(f,e){return f.data=e}function b(f,e){return f.text=e}
var c="data",d="length",g="!",m='"',aa="#",ba="$",ca="%",da="&",n="'",ea="(",fa=")",p="*",ga="+",q=",",r="-",s=".",t="/",ha="0",ia="1",ja="2",la="3",ma="4",na="5",oa="6",pa="7",qa="8",ra="9",sa=":",ta=";",ua="<",u="=",va=">",v="?",w="?123",wa="@",xa="A",ya="B",za="C",Aa="D",Ba="E",Ca="F",Da="G",Ea="H",Fa="I",Ga="J",Ha="K",Ia="L",Ja="M",Ka="N",La="O",Ma="P",Na="Q",Oa="R",Pa="S",Qa="T",Ra="The number of switcher key spec is less than the number of switcher keys in the keyset.",Sa="The number of switcher key spec is more than the number of switcher keys in the keyset.",
Ta="U",Ua="V",Va="W",Wa="X",Xa="Y",Ya="Z",Za="[",$a="\\",ab="]",bb="^",cb="_",db="`",eb="a",fb="b",gb="c",hb="compactkbd-k-",ib="compactkbd-k-key-",x="compactkbd-qwerty",jb="d",kb="e",z="english main layout",lb="english more symbols layout",A="english number and symbol layout",mb="f",nb="g",ob="h",pb="i",qb="inputview-shift-icon",rb="j",sb="k",tb="l",ub="m",B="main layout",vb="more symbols layout",wb="n",C="number and symbol layout",xb="o",yb="p",zb="q",Ab="r",Bb="s",Cb="t",Db="u",Eb="v",Fb="w",Gb=
"x",Hb="y",Ib="z",Jb="{",Kb="|",Lb="}",Mb="~",D="\u00a1",E="\u00a2",F="\u00a3",Nb="\u00a5",Ob="\u00a7",Pb="\u00a9",G="\u00ab",Qb="\u00ae",Rb="\u00b0",Sb="\u00b1",Tb="\u00b2",Ub="\u00b3",Vb="\u00b6",Wb="\u00b7",Xb="\u00b9",H="\u00bb",Yb="\u00bc",Zb="\u00bd",$b="\u00be",ac="\u00bf",bc="\u00d7",cc="\u00f7",dc="\u0394",ec="\u03a0",fc="\u03c0",gc="\u2013",hc="\u2014",ic="\u2018",jc="\u2019",kc="\u201a",lc="\u201c",mc="\u201d",nc="\u201e",oc="\u2020",pc="\u2021",qc="\u2022",I="\u2026",rc="\u2030",sc="\u2032",
tc="\u2033",J="\u2039",K="\u203a",uc="\u2074",vc="\u207f",wc="\u20ac",xc="\u20b1",yc="\u2105",zc="\u2122",Ac="\u2153",Bc="\u2154",Cc="\u215b",Dc="\u215c",Ec="\u215d",Fc="\u215e",Gc="\u2190",Hc="\u2191",Ic="\u2192",Jc="\u2193",Kc="\u2205",Lc="\u221e",Mc="\u2248",Nc="\u2260",Oc="\u2264",Pc="\u2265",Qc="\u23b7",Rc="\u2605",Sc="\u2660",Tc="\u2663",Uc="\u2665",Vc="\u2666",Wc="\u266a",Xc="\u3001",Yc="\u3002",Zc="\uff01",$c="\uff08",ad="\uff09",bd="\uff0c",cd="\uff1a",dd="\uff1f",ed="\uff5e";
function fd(){for(var f=[{text:zb,hintText:ia,moreKeys:[Na,zb]},{text:Fb,hintText:ja,moreKeys:[Va,Fb]},{text:kb,hintText:la,moreKeys:[Ba,kb]},{text:Ab,hintText:ma,moreKeys:[Oa,Ab]},{text:Cb,hintText:na,moreKeys:[Qa,Cb]},{text:Hb,hintText:oa,moreKeys:[Xa,Hb]},{text:Db,hintText:pa,moreKeys:[Ta,Db]},{text:pb,hintText:qa,moreKeys:[Fa,pb]},{text:xb,hintText:ra,moreKeys:[La,xb]},{text:yb,hintText:ha,moreKeys:[Ma,yb]},gd,{text:eb,hintText:wa,marginLeftPercent:.33,moreKeys:[xa,eb]},{text:Bb,hintText:p,moreKeys:[Pa,
Bb]},{text:jb,hintText:ga,moreKeys:[Aa,jb]},{text:mb,hintText:r,moreKeys:[Ca,mb]},{text:nb,hintText:u,moreKeys:[Da,nb]},{text:ob,hintText:t,moreKeys:[Ea,ob]},{text:rb,hintText:aa,moreKeys:[Ga,rb]},{text:sb,hintText:$c,moreKeys:[Ha,sb]},{text:tb,hintText:ad,moreKeys:[Ia,tb]},hd,id,{text:Ib,hintText:Xc,moreKeys:[Ya,Ib]},{text:Gb,hintText:cd,moreKeys:[Wa,Gb]},{text:gb,hintText:m,moreKeys:[za,gb]},{text:Eb,hintText:dd,moreKeys:[Ua,Eb]},{text:fb,hintText:Zc,moreKeys:[ya,fb]},{text:wb,hintText:ed,moreKeys:[Ka,
wb]},{text:ub,hintText:s,moreKeys:[Ja,ub]},{text:Zc,moreKeys:[D]},{text:dd,moreKeys:[ac]},jd,L,kd,M,{text:bd,isGrey:!0},ld,{text:Yc,isGrey:!0},L,md],e=0;9>=e;e++)f[e].moreKeysShiftOperation=2;for(e=11;19>=e;e++)f[e].moreKeysShiftOperation=2;for(e=22;28>=e;e++)f[e].moreKeysShiftOperation=2;return f}
function nd(){return[{text:Mb},{text:db},{text:Kb},{text:qc,moreKeys:[Wc,Uc,Sc,Vc,Tc]},{text:Qc},{text:fc,moreKeys:[ec]},{text:cc},{text:bc},{text:Vb,moreKeys:[Ob]},{text:dc},gd,{text:F,marginLeftPercent:.33},{text:E},{text:wc},{text:Nb},{text:bb,moreKeys:[Hc,Jc,Gc,Ic]},{text:Rb,moreKeys:[sc,tc]},{text:u,moreKeys:[Nc,Mc,Lc]},{text:Jb},{text:Lb},hd,L,{text:$a},{text:Pb},{text:Qb},{text:zc},{text:yc},{text:Za},{text:ab},{text:D},{text:ac},L,L,{text:ua,isGrey:!0,moreKeys:[J,Oc,G]},M,{text:va,isGrey:!0,
moreKeys:[K,Pc,H]},ld,{text:q,isGrey:!0},{text:s,isGrey:!0,moreKeys:[I]},md]}
function od(){return[{text:ia,moreKeys:[Xb,Zb,Ac,Yb,Cc]},{text:ja,moreKeys:[Tb,Bc]},{text:la,moreKeys:[Ub,$b,Dc]},{text:ma,moreKeys:[uc]},{text:na,moreKeys:[Ec]},{text:oa},{text:pa,moreKeys:[Fc]},{text:qa},{text:ra},{text:ha,moreKeys:[vc,Kc]},gd,{text:wa,marginLeftPercent:.33},{text:aa},{text:ba,moreKeys:[E,F,wc,Nb,xc]},{text:ca,moreKeys:[rc]},{text:da},{text:r,moreKeys:[cb,gc,hc,Wb]},{text:ga,moreKeys:[Sb]},{text:ea,moreKeys:[Jb,ua,Za]},{text:fa,moreKeys:[Lb,va,ab]},hd,L,{text:$a},{text:u},{text:p,
moreKeys:[oc,pc,Rc]},{text:m,moreKeys:[lc,nc,mc,G,H]},{text:n,moreKeys:[ic,kc,jc,J,K]},{text:sa},{text:ta},{text:g,moreKeys:[D]},{text:v,moreKeys:[ac]},L,L,{text:cb,isGrey:!0},M,{text:t,isGrey:!0},ld,{text:q,isGrey:!0},{text:s,isGrey:!0,moreKeys:[I]},md]}
function N(f){for(var e=[],y={},k=0;k<f[c][d];k++){var l=f[c][k];l==M&&(l.toKeyset=f.id.split(s)[0]);var h;h=l;h.id=l.id?l.id:ib+k;h.type||(h.type=22);var l={},ka=void 0;for(ka in h)l[ka]=h[ka];h={spec:l};e.push(h);y[h.spec.id]=hb+k}return{keyList:e,mapping:y,layout:f.layout}}function O(f,e){for(var y=0,k=0;k<f[d];k++)if(f[k]==L){if(y>=e[d]){console.error(Ra);return}var l=e[y++],h;for(h in f[k])l[h]=f[k][h];f[k]=l}y<e[d]-1&&console.error(Sa)};var gd={iconCssClass:"inputview-backspace-icon",type:13,id:"Backspace"},hd={iconCssClass:"inputview-enter-icon",type:12,id:"Enter"},md={iconCssClass:"inputview-hide-keyboard-icon",type:19,id:"HideKeyboard"},id={toState:1,iconCssClass:qb,type:5,id:"ShiftLeft",supportSticky:!0},jd={toState:1,iconCssClass:qb,type:5,id:"ShiftRight",supportSticky:!0},ld={name:" ",type:11,id:"Space"},L={type:21},M={iconCssClass:"inputview-menu-icon",type:26,id:"Menu"},kd={iconCssClass:"inputview-globe-icon",type:27,id:"Globe"};var P={id:"pinyin-zh-CN.compact.qwerty",layout:x};a(P,fd());for(var Q={id:"pinyin-zh-CN.en.compact.qwerty",layout:x},R=fd(),S=0;9>=S;S++)R[S].moreKeys.pop();for(S=11;19>=S;S++)R[S].moreKeys.pop();for(S=22;28>=S;S++)R[S].moreKeys.pop();R[12].hintText=p;R[14].hintText=r;R[16].hintText=t;R[18].hintText=ea;R[19].hintText=fa;R[22].hintText=n;R[23].hintText=sa;R[25].hintText=v;R[26].hintText=g;R[27].hintText=Mb;R[28].hintText=I;b(R[29],g);b(R[30],v);b(R[35],q);b(R[37],s);a(Q,R);
var T={id:"pinyin-zh-CN.compact.symbol",layout:x},U=od();b(U[13],Nb);U[13].moreKeys=[ba,E,F,wc,xc];b(U[15],da);b(U[18],$c);U[18].moreKeys=["\uff5b","\u300a","\uff3b","\u3010"];b(U[19],ad);U[19].moreKeys=["\uff5d","\u300b","\uff3d",Xc];b(U[22],Xc);b(U[25],lc);U[25].moreKeys=[m,G];b(U[26],mc);U[26].moreKeys=[m,H];b(U[27],cd);b(U[28],"\uff1b");b(U[29],ic);U[29].moreKeys=[n,J];b(U[30],jc);U[30].moreKeys=[n,K];b(U[33]," \u2014");U[33].moreKeys=void 0;b(U[35],I);U[35].moreKeys=void 0;b(U[37],bd);
b(U[38],Yc);a(T,U);var V={id:"pinyin-zh-CN.en.compact.symbol",layout:x};a(V,od());var W={id:"pinyin-zh-CN.compact.more",layout:x},X=nd();b(X[0],ed);b(X[15],Rb);X[15].moreKeys=[sc,tc];b(X[16],"\u300e");X[16].moreKeys=void 0;b(X[17],"\u300f");X[17].moreKeys=void 0;b(X[18],"\uff5b");b(X[19],"\uff5d");b(X[22],"\uff0f");X[22].moreKeys=void 0;b(X[27],"\uff3b");b(X[28],"\uff3d");b(X[29],"\u3010");X[29].moreKeys=void 0;b(X[30],"\u3011");X[30].moreKeys=void 0;b(X[33],"\u300a");X[33].moreKeys=[J,Oc,G];
b(X[35],"\u300b");X[35].moreKeys=[K,Pc,H];b(X[37],bd);b(X[38],Yc);a(W,X);var Y={id:"pinyin-zh-CN.en.compact.more",layout:x};a(Y,nd());var Z=google.ime.chrome.inputview.onConfigLoaded;O(P[c],[{name:w,toKeyset:T.id,toKeysetName:C},{toKeyset:Q.id,toKeysetName:z,iconCssClass:"inputview-switcher-chinese"}]);var $=N(P);$.id=P.id;$.showMenuKey=!0;Z($);O(Q[c],[{name:w,toKeyset:V.id,toKeysetName:A},{toKeyset:P.id,toKeysetName:B,iconCssClass:"inputview-switcher-english"}]);$=N(Q);$.id=Q.id;$.showMenuKey=!0;
Z($);O(T[c],[{name:"~[<",toKeyset:W.id,toKeysetName:vb},{name:"~[<",toKeyset:W.id,toKeysetName:vb},{name:"abc",toKeyset:P.id,toKeysetName:B}]);$=N(T);$.id=T.id;$.showMenuKey=!1;$.noShift=!0;Z($);O(V[c],[{name:"~[<",toKeyset:Y.id,toKeysetName:lb},{name:"~[<",toKeyset:Y.id,toKeysetName:lb},{name:"abc",toKeyset:Q.id,toKeysetName:z}]);$=N(V);$.id=V.id;$.showMenuKey=!1;$.noShift=!0;Z($);O(W[c],[{name:w,toKeyset:T.id,toKeysetName:C},{name:w,toKeyset:T.id,toKeysetName:C},{name:"abc",toKeyset:P.id,toKeysetName:B}]);
$=N(W);$.id=W.id;$.showMenuKey=!1;$.noShift=!0;Z($);O(Y[c],[{name:w,toKeyset:V.id,toKeysetName:A},{name:w,toKeyset:V.id,toKeysetName:A},{name:"abc",toKeyset:Q.id,toKeysetName:z}]);$=N(Y);$.id=Y.id;$.showMenuKey=!1;$.noShift=!0;Z($);})();
