#!/bin/sh
# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# For good hygiene, clean up on job stop.
for cmd in iptables ip6tables ; do
  $cmd -D INPUT -p tcp --dport 22 -j ACCEPT -w || true
done
