// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports Google voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'pipelineFile': '/voice_lstm_ko-KR/lstm/pipeline',
  'prefix': '',
  'voiceType': 'lstm',
  'cacheToDisk': false,
  'lang': 'ko-KR',
  'gender': 'male',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_lstm_ko-KR.zvoice',
      'url': '',
      'md5sum': '91d48a54ad3cbf85d4312b4c4f9ba728',
      'size': 6028447,
    },
  ],
});
